---
title: "STATS 506 HW 4"
author: "Calder Moore"
format: pdf
editor: visual
---

# STATS 506 HW 4

## Problem 1 - Tidyverse: New Zealand

### a)

```{r}
library(tidyverse)
library(nzelect)

nztib <- tibble(vote = nzge$votes, year = nzge$election_year, type = nzge$voting_type) %>%
          group_by(type, year) %>%
          summarise(vote_total = sum(vote)) %>%
          arrange(desc(vote_total))

nztib
```

### b)

```{r}
vote2014 <- tibble(vote = nzge$votes, year = nzge$election_year, party = nzge$party) %>%
              group_by(year, party) %>%
              filter(year == 2014) %>%
              summarise(vote_total = sum(vote)) %>%
              mutate(vote_percent = 100*vote_total/sum(vote_total))
              
vote2014          
```

### c)

```{r}
win <- tibble(vote = nzge$votes, year = nzge$election_year, party = nzge$party, type = nzge$voting_type) %>%
              group_by(year, party, type) %>%
              summarise(vote_total = sum(vote)) %>%
              group_by(year) %>%
              mutate(vote_percent = 100*vote_total/sum(vote_total)) %>%
              group_by(year, type) %>%
              mutate(winner = party[which.max(vote_percent)]) %>%
              slice_max(vote_percent) %>%
              select(year, type, winner)

win  
```

## Problem 2 - Tidyverse: Tennis

### a)

```{r}
tennis <- read.csv("atp_matches_2019.txt")

tourney_count <- tennis %>%
  mutate(tourney_date = ymd(tourney_date)) %>%
  filter(year(tourney_date) == 2019) %>%
  distinct(tourney_date)

nrow(tourney_count)
```

There were 48 tournaments in 2019

### b)

```{r}
winners <- tennis %>%
  group_by(tourney_id) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  count(winner_name, sort = TRUE) %>%
  filter(n > 1)

nrow(winners)

max(winners$n)
```

25 players have won more than one tournament, and the most winning player has won 7 tournaments.

### c)

```{r}

```










